import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AdrenalineHub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="min-h-screen w-full bg-gradient-to-b from-[#1e1e48] via-[#1d4e7a] to-[#1483a6] flex justify-center items-center p-4">
            <div className="w-full max-w-sm">
            {children}
            </div>
        </div>
      </body>
    </html>
  );
}
